### ISSUE TITLE
After creating second plugin, wordup export hangs

### ISSUE THREAD

**Issue by jackjwilliams** [wordup-dev/wordup-cli#3]
I was the one that opened https://github.com/wordup-dev/wordup-cli/issues/2

After creating my second plugin, the `wordup export installation` command seems to just hang at `Write wordup-archive.json for WP-Version: 5.2`.

It never exits back to the console or finishes.

OS: Windows

Console:

```
C:\Projects\Personal\techlyplugins\techly-tech-specs [master ≡ +0 ~0 -2 | +0 ~1 -0 !]> wordup export installation
Starting techly-tech-specs_db_1 ... done
Starting techly-tech-specs_wordpress_1 ... done
Parsed wordup package.json with slug: techly-tech-specs/techly-tech-specs.php
Success: Exported to '/tmp/wordup-installation/db-snapshot-1558328264.sql'.
Write wordup-archive.json for WP-Version: 5.2
```

And now it's been sitting there for 5 minutes. Any ideas why this might be?

**Comment by shry** [comment]
If I understand you right:
You set up 2 different wordup projects. And the installation export of the second project is not working? 

Some follow up questions:
* Does the installation export of the first project work?
* Does `wordup export src` work on both projects?

What you could try also: 
* You could delete the installation and reinstall it `wordup stop -delete`:  Keep in mind that media, posts etc. of your WordPress installation are lost afterwards.
* Delete the wordup docker-containers: `docker images` and `docker rmi [id-of-wordup-container]`

**Comment by jackjwilliams** [comment]
Correct

Followup answers:
* The export no longer works on the first project (it hangs as well)
* `wordup export src` does not work on the first or second project (both hang at `Parsed wordup package.json with slug: {SLUG}`)

It's as if node isn't letting go of the process. I'll try your other recommendations later when I have time.

**Comment by jackjwilliams** [comment]
I did some more digging, cloned the project and attempted to run the tests. It seems export is failing for me:

```
 1) export
       Test final shell.exec which runs docker compose:
     TypeError: Cannot read property 'listeningOnPort' of undefined
      at ExportCommand.run (src\commands\export.js:1:4521)
      at ExportCommand._run (node_modules\@oclif\command\lib\command.js:35:31)
      at <anonymous>
```

I npm install -g'd from my folder and dropped a console.log at line 21 of export.js: 

```
console.log(project.config);
project.prepareDockerComposeUp(project.config.listeningOnPort)
```

Which confuses me because it appears to be there:

```
{ name: 'techly-tech-specs',
  slugName: 'techly-tech-specs',
  path: 'C:\\Projects\\Personal\\techlyplugins\\techly-tech-specs',
  installedOnPort: '8000',
  listeningOnPort: '8000',
  scaffoldOnInstall: false,
  created: 1558319161 
}
```
// ----- IT HANGS HERE ------
WP_CLI::log('Write wordup-archive.json for WP-Version: '.$wp_version);
            
//Move src back to destination, if available 
WP_CLI::launch('unlink '.$project_tmp_path);
WP_CLI::launch('mkdir '.$project_tmp_path);
WP_CLI::launch('cp -a /src/. '.$project_tmp_path);

Is there supposed to be a dot (.) at `cp -a /src/. ' <-- a dot inside the single quotes?

**Comment by shry** [comment]
Thank you very much for your help. 
I also did some investigation. For sure the bug is in the [wordup-wp-cli](https://github.com/wordup-dev/wordup-wp-cli). 
If the export command doesn't finish correctly, for whatever reason -> The file structure in the docker container is corrupted. But i think i can solve this problem.
Have you tried to reinstall the whole installation with: `wordup stop --delete` ?

**Comment by jackjwilliams** [comment]
I did try that method but it didn't work

**Comment by shry** [comment]
Ok, this makes it a little bit more complicated ;-) 

> Is there supposed to be a dot (.) at 'cp -a /src/. ' <-- a dot inside the single quotes? 

The dot is correct, it copies the content of a folder, without the folder itself. 

Furthermore I think it's a windows specific bug, because i cannot reproduce this issue on my system.

**Comment by shry** [comment]
I have released a new version , which should prevent some export failures. I don't know if your issue will be solved, but it's worth a try.

**Comment by jackjwilliams** [comment]
Thanks @shry, I will give it a go

**Comment by jackjwilliams** [comment]
Thanks, I tried again but it still didn't work. On a good note: Creating a new wordup instance, without modifying anything, exported fine. 

I've got a private repo (techly-tech-specs), that I've invited you to. If you want to see my projects layout. I thought it may have something to do with my structure or added dependencies. I use a webpack / babel friendly build process, so I can use all the ES6 goodness.

**Comment by jackjwilliams** [comment]
I think I may see whats happening. It's trying to copy my 500MB node_modules from my src folder in this command:

`WP_CLI::launch('cp -a /src/. /tmp/'.$project_folder_name);`

**Comment by shry** [comment]
That is the issue, for sure!!!  Because this kind of big file size in a zip file makes always problems.

But this should only be valid for `wordup export installation`. 

The export for `wordup export src` should be ignoring node_modules. Because all files in `.distignore` will be ignored. But you said that this doesn't work either. Am i right?

Your code looks good, i don't see a problem there.

I will change the export installation function so that it will also ignore the `.distignore` files, that should solve the problem.

**Comment by shry** [comment]
I have released a new version. I have deleted the file copying and node_modules will not be exported if it's in `.distignore`. 
Although i have tested it, with a big node_modules folder it will take longer. This is because im using the official dist-archive wp-cli command, which seems to perform poorly. Perhaps i will rewrite this function in the near feature.
