### ISSUE TITLE
Cannot Export Installation

### ISSUE THREAD

**Issue by palomnik** [wordup-dev/wordup-cli#4]
Trying to export the site (installation) via "wordup export installation" I get:

$ wordup export installation

--- Currently running wordup projects: test ---

Starting test_db_1   ... done
Starting test_mail_1 ... done
Starting test_wordpress_1 ... done
Parsed wordup package.json with slug: test
Creating DB snapshot ...
Writing wordup-archive.json for WP-Version: 5.2.2
events.js:177
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/Users/palomnik/Virtual_Machines/Docker/Test/test/dist/installation-1560940676.tar.gz'
Emitted 'error' event at:
    at /usr/local/lib/node_modules/wordup-cli/node_modules/graceful-fs/graceful-fs.js:207:14
    at /usr/local/lib/node_modules/wordup-cli/node_modules/graceful-fs/graceful-fs.js:258:16
    at FSReqCallback.oncomplete (fs.js:153:23) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/palomnik/Virtual_Machines/Docker/Test/test/dist/installation-1560940676.tar.gz'
}

**Comment by shry** [comment]
Some follow up questions: 
* Do you have the latest version of wordup-cli installed?
* Does `wordup export` work for you (plugin/theme export)?
* When you setup a fresh new wordup project and run `wordup export installation` does this work? 

You see this error, because the zip-file creation does not work and it doesn't find the file. I will catch this error in the next patch. But this doesn't fix the problem in general.

Sometimes it helps also to run `wordup stop --delete` and reinstall the whole project, but be aware that you are losing created content in your wordpress installation.

Thank you for your help 👍

**Comment by palomnik** [comment]
I'm actually developing sites with customized themes, rather than themes or plugins.  In fact it would be good if "site" was an option in the setup (I've been choosing themes, just to choose something).
I completely pruned docker, and I'm installing again.  Fortunately, I can get stuff in and out using duplicator pro.  I hope that the connect will support duplicator in the future.

**Comment by shry** [comment]
Ok, I understand that. 
The advice of WordPress is to use Child-Themes if you want to customize a theme. This use-case is covered in wordup. Because in a theme project you just define your parent theme in the package.json and setup your child theme according to https://developer.wordpress.org/themes/advanced-topics/child-themes/ 

Perhaps i will integrate the 'site' - feature in the future. I will set in on my list. Thank you

**Comment by palomnik** [comment]
Using a child theme "used" to be the main way to customize a theme.  However, with more modern highly configurable themes like generatepress, this is no longer necessary, as most aspects of the theme can be controlled in customization, and CSS and Theme directives can be added without modifying the theme base.  I have done many child themes, but since moving to generatepress, this is no longer necessary in most cases.  It is also possible to download customized settings as a single json file.

**Comment by palomnik** [comment]
I meant to mention:  wordup is the best docker wordpress system that I have tried.  Thank you for doing this!

**Comment by shry** [comment]
> I meant to mention: wordup is the best docker wordpress system that I have tried. Thank you for doing this!

Thank you very much :)

> I'm trying to attach phpmyadmin to a wordup site, but I am getting the db link wrong. Can you tell me what the correct command should be? I am trying:

There is an undocumented function in wordup which you could use to extend the internal docker-compose setup:

Just create a file called `docker-compose.yml` in the root folder of your project. And you can extend the docker setup of your project with custom containers of your choice. For Phpmyadmin the file should look like this:

```
version: '3'

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      - PMA_HOST=db
    ports:
      - 8080:80
```

Afterwards you just use all wordup commands like before. The password and username for the phpmyadmin login is both times: wordpress

**Comment by shry** [comment]
Please check out v0.5.0, this issue should be fixed.

**Comment by jay-manday** [comment]
I've spent like an embarrassing amount of time looking for a simple way to do this, the closest i've gotten before this was working with postlights excellent starter, thank you for this proj!

**Comment by shry** [comment]
I'm happy to hear that :) 
Please be aware that the wordup docker containers are not production ready. It's currently just for development purposes. But I thought about the same thing, what you had in your mind. And i'm currently developing some cool stuff, and one thing will be easy deployment to cloud providers :)
